-- GENERATED by tools/kanji_seed_sql.py -- do not edit by hand.
-- Pure ASCII: kanji and kana are written as U&'\XXXX' escapes so the
-- file survives being piped through a Windows console.
-- Source: unity-client/Assets/Resources/kanji_content.json
-- schemaVersion 1, sha256 386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb, 40 kanji.
-- Idempotent: insert or update every row. Rows of kanji that left the
-- json are NOT deleted (projected trials may still point at them).
BEGIN;
INSERT INTO kanji_items (kanji_id, kanji_char, meaning, target_reading, role, experimental_set, strokes, morae, assembly_groups, common_readings, perimetric_complexity, imageability_glyph, imageability_object, discovery_type, textbook_lesson, content_schema_version, content_sha256) VALUES
    ('KANJI_AME', U&'\96E8', 'rain', U&'\3042\3081', 'EXPERIMENTAL', 'B', 8, 2, 3, 2, 310.9, 5, 2, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_ASHI', U&'\8DB3', 'leg, foot', U&'\3042\3057', 'EXPERIMENTAL', 'C', 7, 2, 3, 3, 180.4, 3, 3, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_CHA', U&'\8336', 'tea', U&'\3061\3083', 'RESERVE', NULL, 9, 2, 3, 2, 311.7, 1, NULL, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_GAKU', U&'\5B66', 'study', U&'\30AC\30AF', 'RESERVE', NULL, 8, 2, 3, 2, 261.4, 3, NULL, 'Pictographic', 'L2-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_GO', U&'\4E94', 'five', U&'\3054', 'TUTORIAL', NULL, 4, 1, 2, 2, 162.6, NULL, NULL, 'None', 'L3', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_HANA', U&'\82B1', 'flower', U&'\306F\306A', 'EXPERIMENTAL', 'C', 7, 2, 3, 2, 226.4, 2, 5, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_HI', U&'\706B', 'fire', U&'\3072', 'EXPERIMENTAL', 'A', 4, 1, 3, 2, 196.9, 5, 2, 'Pictographic', 'L2-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_HITO', U&'\4EBA', 'person', U&'\3072\3068', 'EXPERIMENTAL', 'C', 2, 2, 2, 3, 117.8, 5, 5, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_ICHI', U&'\4E00', 'one', U&'\3044\3061', 'TUTORIAL', NULL, 1, 2, 1, 3, 52.9, NULL, NULL, 'None', 'L3', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_ISHI', U&'\77F3', 'stone', U&'\3044\3057', 'EXPERIMENTAL', 'A', 5, 2, 2, 2, 178.9, 5, 5, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_ITO', U&'\7CF8', 'thread', U&'\3044\3068', 'RESERVE', NULL, 6, 2, 2, 2, 277.6, 5, NULL, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KAI', U&'\8C9D', 'shellfish', U&'\304B\3044', 'RESERVE', NULL, 7, 2, 2, 2, 210.9, 5, NULL, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KAWA', U&'\5DDD', 'river', U&'\304B\308F', 'RESERVE', NULL, 3, 2, 3, 2, 133.8, 4, NULL, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KI', U&'\6728', 'tree', U&'\304D', 'RESERVE', NULL, 4, 1, 2, 3, 195.8, 5, NULL, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KIN', U&'\91D1', 'gold', U&'\304D\3093', 'RESERVE', NULL, 8, 2, 3, 3, 285.6, 3, NULL, 'Pictographic', 'L2-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KO', U&'\5B50', 'child', U&'\3053', 'RESERVE', NULL, 3, 1, 2, 3, 143.5, 3, NULL, 'Pictographic', 'L2-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KOME', U&'\7C73', 'rice', U&'\3053\3081', 'RESERVE', NULL, 6, 2, 3, 3, 247.2, 3, NULL, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KUCHI', U&'\53E3', 'mouth', U&'\304F\3061', 'RESERVE', NULL, 3, 2, 2, 2, 100.6, 5, NULL, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_KURUMA', U&'\8ECA', 'car', U&'\304F\308B\307E', 'EXPERIMENTAL', 'A', 7, 3, 3, 2, 245.8, 2, 5, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_ME', U&'\76EE', 'eye', U&'\3081', 'RESERVE', NULL, 5, 1, 2, 2, 162.9, 5, NULL, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_MIMI', U&'\8033', 'ear', U&'\307F\307F', 'RESERVE', NULL, 6, 2, 2, 2, 176.1, 4, NULL, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_MIZU', U&'\6C34', 'water', U&'\307F\305A', 'RESERVE', NULL, 4, 2, 2, 2, 214.4, 4, NULL, 'Pictographic', 'L2-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_MON', U&'\9580', 'gate', U&'\3082\3093', 'EXPERIMENTAL', 'B', 8, 2, 2, 2, 190.3, 5, 5, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_MONO', U&'\7269', 'thing', U&'\3082\306E', 'RESERVE', NULL, 8, 2, 3, 3, 343.3, 1, NULL, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_NI', U&'\4E8C', 'two', U&'\306B', 'TUTORIAL', NULL, 2, 1, 2, 2, 58.2, NULL, NULL, 'None', 'L3', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_NICHI', U&'\65E5', 'sun', U&'\3072', 'RESERVE', NULL, 4, 1, 2, 4, 131.6, 5, NULL, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_NIKU', U&'\8089', 'meat', U&'\306B\304F', 'EXPERIMENTAL', 'C', 6, 2, 2, 1, 271.8, 3, 4, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_ONNA', U&'\5973', 'woman', U&'\304A\3093\306A', 'EXPERIMENTAL', 'B', 3, 3, 3, 4, 179.3, 4, 3, 'Pictographic', 'L2-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_SAKANA', U&'\9B5A', 'fish', U&'\3055\304B\306A', 'RESERVE', NULL, 11, 3, 3, 2, 260.3, 1, NULL, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_SAN', U&'\4E09', 'three', U&'\3055\3093', 'TUTORIAL', NULL, 3, 2, 3, 2, 119.7, NULL, NULL, 'None', 'L3', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_TA', U&'\7530', 'rice field', U&'\305F', 'RESERVE', NULL, 5, 1, 2, 2, 173.3, 5, NULL, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_TAKE', U&'\7AF9', 'bamboo', U&'\305F\3051', 'EXPERIMENTAL', 'A', 6, 2, 2, 2, 184.1, 5, 5, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_TE', U&'\624B', 'hand', U&'\3066', 'EXPERIMENTAL', 'B', 4, 1, 2, 2, 175.0, 2, 3, 'Pictographic', 'L6-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_TORI', U&'\9CE5', 'bird', U&'\3068\308A', 'RESERVE', NULL, 11, 2, 3, 2, 327.6, 1, NULL, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_TSUCHI', U&'\571F', 'ground', U&'\3064\3061', 'RESERVE', NULL, 3, 2, 2, 2, 130.2, 5, NULL, 'Pictographic', 'L2-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_TSUKI', U&'\6708', 'moon', U&'\3064\304D', 'EXPERIMENTAL', 'A', 4, 2, 2, 3, 151.2, 3, 5, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_UMA', U&'\99AC', 'horse', U&'\3046\307E', 'RESERVE', NULL, 10, 2, 3, 2, 273.4, 1, NULL, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_USHI', U&'\725B', 'cow', U&'\3046\3057', 'EXPERIMENTAL', 'C', 4, 2, 2, 2, 159.1, 4, 5, 'Pictographic', 'L7-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_YAMA', U&'\5C71', 'mountain', U&'\3084\307E', 'EXPERIMENTAL', 'B', 3, 2, 2, 2, 109.1, 5, 5, 'Pictographic', 'L1-P', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb'),
    ('KANJI_YON', U&'\56DB', 'four', U&'\3088\3093', 'TUTORIAL', NULL, 5, 2, 2, 3, 200.1, NULL, NULL, 'None', 'L3', 1, '386f74492cad4b6233eec12d9496fcba83b788a5b38ade09d216147f50b854fb')
ON CONFLICT (kanji_id) DO UPDATE SET
    kanji_char = EXCLUDED.kanji_char,
    meaning = EXCLUDED.meaning,
    target_reading = EXCLUDED.target_reading,
    role = EXCLUDED.role,
    experimental_set = EXCLUDED.experimental_set,
    strokes = EXCLUDED.strokes,
    morae = EXCLUDED.morae,
    assembly_groups = EXCLUDED.assembly_groups,
    common_readings = EXCLUDED.common_readings,
    perimetric_complexity = EXCLUDED.perimetric_complexity,
    imageability_glyph = EXCLUDED.imageability_glyph,
    imageability_object = EXCLUDED.imageability_object,
    discovery_type = EXCLUDED.discovery_type,
    textbook_lesson = EXCLUDED.textbook_lesson,
    content_schema_version = EXCLUDED.content_schema_version,
    content_sha256 = EXCLUDED.content_sha256,
    loaded_at = now();
COMMIT;
