#!/usr/bin/env python3
"""
Seed of the `kanji_items` catalogue (schema v1, F3.4) from the content contract.

    python tools/kanji_seed_sql.py                 # writes database/seed_kanji_items.sql
    python tools/kanji_seed_sql.py --out -         # to stdout

Reads unity-client/Assets/Resources/kanji_content.json -- the same file Unity
reads -- and writes an idempotent upsert. `tools/kanji_metrics.py --export`
calls it right after writing the json, so the two can never come from
different content (decided 1 Oct 2026). Standard library only: it runs on the
host, in the kanji-tools container or anywhere with Python 3.10+.

Apply after `alembic upgrade head`:

    psql -h localhost -U neuroadaptive -d neuroadaptive_vr -f database/seed_kanji_items.sql

`content_sha256` is the hash of the json bytes, so a row says which version of
the content it came from. The output is deterministic (same json, same file),
so git shows it as changed only when the content changes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_JSON = REPO_ROOT / "unity-client" / "Assets" / "Resources" / "kanji_content.json"
DEFAULT_OUT = REPO_ROOT / "database" / "seed_kanji_items.sql"

ROLES = {"Experimental": "EXPERIMENTAL", "Reserve": "RESERVE", "Tutorial": "TUTORIAL"}

COLUMNS = ("kanji_id", "kanji_char", "meaning", "target_reading", "role", "experimental_set",
           "strokes", "morae", "assembly_groups", "common_readings", "perimetric_complexity",
           "imageability_glyph", "imageability_object", "discovery_type", "textbook_lesson",
           "content_schema_version", "content_sha256")


def _lit(v) -> str:
    """SQL literal. The file is pure ASCII on purpose (1 Oct 2026): piped
    through PowerShell (`Get-Content ... | docker compose exec -T db psql`),
    every kanji and kana arrived as '?', the first row stored '???' and the
    second broke the UNIQUE on kanji_char. Non-ASCII text therefore goes as a
    PostgreSQL Unicode-escape string, U&'\\5C71' for 山, which survives any
    console encoding."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    text = str(v)
    if text.isascii():
        return "'" + text.replace("'", "''") + "'"
    out = []
    for ch in text:
        cp = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == "'":
            out.append("''")
        elif cp < 128:
            out.append(ch)
        elif cp <= 0xFFFF:
            out.append(f"\\{cp:04X}")
        else:
            out.append(f"\\+{cp:06X}")
    return "U&'" + "".join(out) + "'"


def build_sql(json_path: pathlib.Path) -> str:
    raw = json_path.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    blob = json.loads(raw.decode("utf-8"))
    version = int(blob["schemaVersion"])

    rows = []
    for k in blob["kanji"]:
        role = ROLES[k["role"]]
        # The json marks tutorial items with experimentalSet "Tutorial"; the
        # catalogue keeps a set only for EXPERIMENTAL rows (ck_kanji_set_role).
        exp_set = k.get("experimentalSet") if role == "EXPERIMENTAL" else None
        values = (k["id"], k["kanji"], k["meaning"], k["targetReading"], role, exp_set,
                  k["strokes"], k["morae"], k["assemblyGroups"], k["commonReadings"],
                  k.get("perimetricComplexity"), k.get("imageabilityGlyph"),
                  k.get("imageabilityObject"), k["discoveryType"], k.get("textbookLesson"),
                  version, sha)
        rows.append("    (" + ", ".join(_lit(v) for v in values) + ")")
    rows.sort()

    updates = ",\n    ".join(f"{c} = EXCLUDED.{c}" for c in COLUMNS[1:])
    rel = json_path.resolve()
    try:
        rel = rel.relative_to(REPO_ROOT)
    except ValueError:
        pass
    return (
        "-- GENERATED by tools/kanji_seed_sql.py -- do not edit by hand.\n"
        "-- Pure ASCII: kanji and kana are written as U&'\\XXXX' escapes so the\n"
        "-- file survives being piped through a Windows console.\n"
        f"-- Source: {rel.as_posix() if hasattr(rel, 'as_posix') else rel}\n"
        f"-- schemaVersion {version}, sha256 {sha}, {len(rows)} kanji.\n"
        "-- Idempotent: insert or update every row. Rows of kanji that left the\n"
        "-- json are NOT deleted (projected trials may still point at them).\n"
        "BEGIN;\n"
        f"INSERT INTO kanji_items ({', '.join(COLUMNS)}) VALUES\n"
        + ",\n".join(rows) + "\n"
        "ON CONFLICT (kanji_id) DO UPDATE SET\n    "
        + updates + ",\n    loaded_at = now();\n"
        "COMMIT;\n"
    )


def write_seed(json_path: pathlib.Path = DEFAULT_JSON, out: str | pathlib.Path = DEFAULT_OUT) -> str:
    sql = build_sql(pathlib.Path(json_path))
    if str(out) == "-":
        sys.stdout.write(sql)
    else:
        target = pathlib.Path(out)
        target.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n": CRLF on Windows would show the file as modified in git.
        with open(target, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(sql)
    return sql


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", default=str(DEFAULT_JSON), help="kanji_content.json")
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="output .sql, or - for stdout")
    args = ap.parse_args()
    write_seed(pathlib.Path(args.json), args.out)
    if args.out != "-":
        print(f"kanji_items seed written to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
